apiVersion: v1
kind: Pod
metadata:
  name: formik-pod
  labels:
    app: formik-app
    tier: front-end
spec:
  containers:
    - name: formik-container
      image: react-formik-yup-web:latest
      imagePullPolicy: Never  # This stops Kubernetes from attempting to pull from Docker Hub
