apiVersion: apps/v1
kind: Deployment
metadata: # metadata for the Deployment
  name: formik-deployment
spec:
  replicas: 3
  selector: # used to identify the pods that belong to this Deployment
    matchLabels:
      app: formik-app
      tier: front-end # should match the labels in the pod template metadata
  template: # below paste pod yaml file except apiVersion and kind
      metadata: # metadata for the pod template
        name: formik-pod
        labels:
          app: formik-app
          tier: front-end # should match the labels in the selector above
      spec:
        containers:
          - name: formik-container
            image: react-formik-yup-web:latest
            imagePullPolicy: IfNotPresent  # This stops Kubernetes from attempting to pull from Docker Hub
      